# Tensor与module的保存与加载

In [1]:
import torch
from torch import nn

# Tensor的保存与加载

In [2]:
# 序列化到文件
t = torch.randn(5, 5)
print(t)
torch.save(t, './data/t.tensor')
torch.load('./data/t.tensor')

tensor([[-0.3028,  0.8750, -1.2576,  0.0714,  0.8005],
        [ 1.2940,  1.4336,  0.5198, -2.3949, -1.4407],
        [ 0.5091, -1.0287,  0.4933, -2.2236,  1.4829],
        [-0.5200,  0.9021, -0.0429, -1.0872,  0.2069],
        [ 0.0215, -0.1059,  0.2874, -0.6647,  0.4710]])


tensor([[-0.3028,  0.8750, -1.2576,  0.0714,  0.8005],
        [ 1.2940,  1.4336,  0.5198, -2.3949, -1.4407],
        [ 0.5091, -1.0287,  0.4933, -2.2236,  1.4829],
        [-0.5200,  0.9021, -0.0429, -1.0872,  0.2069],
        [ 0.0215, -0.1059,  0.2874, -0.6647,  0.4710]])

In [3]:
from io import BytesIO
t = torch.randn(5, 5)
buffer = BytesIO()
torch.save(t, buffer)
#torch.load(buffer)

# Module的保存与加载

可以单独保存模型的参数，也可以把整个模型保存起来

In [4]:
from torch import nn

In [5]:
model = nn.Sequential(nn.Linear(25, 100), nn.ReLU(), nn.Linear(100, 10))
torch.save(model.state_dict(), './data/mlp-params.pt')

In [6]:
params = torch.load('./data/mlp-params.pt')
# 现在的模型加载一份离线的参数
model.load_state_dict(params)

<All keys matched successfully>

In [7]:
# 直接把一个网络保存下来
torch.save(model, './data/mlp-model.pt')

In [8]:
print(torch.load('./data/mlp-model.pt'))

Sequential(
  (0): Linear(in_features=25, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=10, bias=True)
)


# 使用GPU

In [9]:
gpu_model = model.to(device='cuda:0')

In [10]:
input = torch.randn(1, 25, device='cuda:0')
gpu_model(input)

tensor([[-0.1885,  0.3525,  0.5501,  0.1224, -0.1966, -0.3041,  0.1034, -0.1547,
          0.2408,  0.2632]], device='cuda:0', grad_fn=<AddmmBackward>)

In [7]:
# GPU下保存的Tesnor或model，加载回来时，还是在对应的GPU上
t = torch.randn(3,4,device='cuda')
torch.save(t, './data/t-cuda.pt')
t = torch.load('./data/t-cuda.pt')
t.device

device(type='cuda', index=0)