# Tensor的创建


In [1]:
import torch
import numpy as np

在Pytorch中我们可以有多种方法来创建Tensor，常用的包括下面几种：

- 从已有的scalar、list、tuple、numpy.array来创建
- 用`arange`、`linspace`、`logspace`等创建一维数列Tensor
- 用`ones`、`zeros`、`eye`、`full`、`empty`等来创建特别填充值的多维Tensor
- 用随机数来创建指定形状的Tensor

# 从现有数据来创建一个Tensor

我们可以使用`torch.tensor()`函数来从已有的一个array_like的data来创建一个Tensor

In [2]:
# 从list创建
torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [3]:
# 从tuple创建
torch.tensor((1,2,3))

tensor([1, 2, 3])

In [4]:
# 从numpy.array创建
torch.tensor(np.array([1,2,3,4,5]), dtype=torch.float32, device='cuda:0')

tensor([1., 2., 3., 4., 5.], device='cuda:0')

需要注意的是，无论是从python的内置序列创建，还是从numpy.array来创建，创建出来的Tensor都是复制了原数据的内容。

如果我们希望，创建的Tensor不额外分配存储空间，而是和之前的numpy.array共享存储，那么可以使用`as_tensor`方法

In [5]:
arr = np.array([1,2,3,4,5])
t = torch.as_tensor(arr)
# 对于Tensor的数据改动，也会影响在ndarray上
t[0] = 6
print(arr)

[6 2 3 4 5]


不过使用`as_tensor`后，能共享底层存储的，前提是，as_type方法中指定的`dtype`和`device`和原ndarry是一致的。

In [6]:
arr = np.array([1,2,3,4,5])
t = torch.as_tensor(arr, dtype=torch.float32)# 这种情况下，并不会共享底层存储
t[0] = 6
print(arr)

[1 2 3 4 5]


In [42]:
il = [1,2,3,4,5]
print(f'ndarray的默认整数类型为:{np.array(il).dtype}')
print(f'tensor的默认整数类型为: {torch.tensor(il).dtype}')

fl = [1.0,2.0,3.0,4.0,5.0]
print(f'ndarray的默认整数类型为:{np.array(fl).dtype}')
print(f'tensor的默认整数类型为: {torch.tensor(fl).dtype}')

ndarray的默认整数类型为:int64
tensor的默认整数类型为: torch.int64
ndarray的默认整数类型为:float64
tensor的默认整数类型为: torch.float32


# `torch.tensor()`和`torch.Tensor()`的区别

`torch.Tensor`实际上是`torch.FloatTensor`，用它来创建新的Tensor时，实际调用的是构造函数，它会默认以`torch.float32`来作为`dtype`。而`torch.tensor`会根据`data`的类型自动推断。

In [7]:
l = [1,2,3,4,5]
print(torch.Tensor(l).dtype)
print(torch.tensor(l).dtype)

torch.float32
torch.int64


# 创建特别填充值的Tensor

## torch.arange

torch.arange(start=0, end, step=1)用于创建一个区间范围的Tensor

In [8]:
print(torch.arange(5))
print(torch.arange(1,5))
print(torch.arange(1, 20, 3))

tensor([0, 1, 2, 3, 4])
tensor([1, 2, 3, 4])
tensor([ 1,  4,  7, 10, 13, 16, 19])


In [9]:
# 如果start、end以及step中有浮点数，则创建出来的是FloatTensor
torch.arange(1, 3.5, 0.5)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000])

注意上面是没有包括3.5那个点的

## torch.linspace

`torch.linspace`与`torch.arange`有点类似，都指定一个起点，一个终点，和一个步长。但`linspace`里步长最终指定了生成的一维Tensor中元素的个数

```python
linspace(start(float),end(float),steps(int))
```
另外需要注意的是`torch.linspace`生成的一定是一个浮点数的Tensor，而且和`torch.arange`不同的是：`linspace`生成的Tensor是包括末点值的（inclusive）

In [10]:
torch.linspace(3,10,5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

## torch.logspace

`torch.logspace`和`torch.linspace`行为类似，区别在于`logspace`生成的序列的范围的起始与终点是一个以`base`为底，`start`和`end`为指数的数字。

```python
logspace(start, end, stpes, base=10.0) -> Tensor
```

## torch.ones、torch.zeros、torch.emtpy

它们三个都是用于创建一个指定`size`的Tensor，分别以1、0和未初始化的值来填充

它们三个返回的都是`FloatTensor`

In [11]:
print(torch.ones(2,2))
print(torch.zeros(3,4))
print(torch.empty(3,3))

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[-4.2743e+12,  4.5893e-41, -8.3130e+17],
        [ 3.0652e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


## torch.eye

`torch.eye`返回的是一个2d的对角线为1，其他值都为0的Float矩阵Tensor

In [12]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## torch.full

`torch.full`返回的是一个指定`size`和填充值的Tensor，Tensor的dtype是由填充值的类型来推导的。

```python
'''
Args:
  size(int...): a list ,tuple or torch.Size
  fill_vale(Scalar)
'''
full(size, fill_value)
```

In [13]:
torch.full((2,3),1.0)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

# 使用随机数来创建Tensor

## torch.normal

`torch.normal`返回一个正态分布产生在的随机数填充的Tensor，它一共有4种参数传递方式

第一种是:

```python
'''
Args:
    mean (Tensor): the tensor of per-element means
    std (Tensor): the tensor of per-element standard deviations
'''
norm(mean, std)
```
生成的Tensor的size和mean和std的size是一致的，其中每个元素都是通过对应位置的mean和std形成的正态分布来随机产生的。

mean和std两个Tensor的shape不需要一致，但是元数数量需要一致，当shape不一致时，以mean的shape作为最终生成的Tensor的shape

In [14]:
mean = torch.arange(12).reshape(3,4).to(dtype=torch.float32)
std = torch.linspace(0,1,mean.numel())
torch.normal(mean, std)

<ipython-input-14-49245019fc67>:3: UserWarning: std and mean have the same number of elements, but are not broadcastable. This was previously a supported mode of operation, but is now deprecated and the support will be removed in version 1.6 release. Note that the current implementation reshapes std to the shape of mean, which may be incur data copies. Please ensure that std and mean are broadcastable to avoid these issues. (Triggered internally at  /opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/DistributionTemplates.h:189.)
  torch.normal(mean, std)


tensor([[ 0.0000,  0.9364,  1.9420,  2.9102],
        [ 4.0290,  4.3689,  5.2698,  7.6781],
        [ 7.8305,  8.5575, 10.7068, 12.5202]])

第二种是：

```python
'''
Args:
    mean (float, optional): the mean for all distributions
    std (Tensor): the tensor of per-element standard deviations
'''
normal(mean=0.0, std, *, out=None) -> Tensor
```
这种参数传递用法，与上面的区别就是mean变成一个Scalar，那么说明每个元素来共享一个mean值。

在这种情况下，生成的Tensor的shape就行std保持一致的了。

In [15]:
torch.normal(1.0, std)

tensor([ 1.0000,  0.9540,  0.7664,  1.0074,  0.7044,  0.8077,  1.3776,  2.2947,
         2.7416,  2.0305,  2.3241, -0.1520])

第三种：

```python
'''
Args:
    mean (Tensor): the tensor of per-element means
    std (float, optional): the standard deviation for all distributions
'''
normal(mean, std=1.0, *, out=None) -> Tensor
```
这种情况和第二种情况，恰恰相反了，std变成了每个元素共享的。

In [16]:
torch.normal(mean, 0.5)

tensor([[-0.2012,  1.6828,  1.9805,  2.8949],
        [ 2.7657,  6.4303,  5.6291,  7.1419],
        [ 8.1036,  9.3677, 10.5676, 10.7179]])

第四种：

```python
'''
Args:
    mean (float): the mean for all distributions
    std (float): the standard deviation for all distributions
    size (int...): a sequence of integers defining the shape of the output tensor.
'''
normal(mean, std, size, *, out=None) -> Tensor
```
这种情况下，所有的元素都共享mean和std，最终Tensor的形状是由`size`来决定的

In [17]:
torch.normal(0, 1, (3,4))

tensor([[ 0.3704, -1.0554, -0.4917,  0.3783],
        [ 0.3406,  1.5351, -0.5526, -0.9879],
        [-0.5488,  1.2171, -0.1122,  0.2516]])

## torch.rand、torch.randn

`rand`直接生成指定形状的Tensor，其中每个元素都是由`[0,1)`均匀分布来随机产生。

`randn`直接生成指定形状的Tensor，其中每个元素都是由标准正态分布来随机产生。

In [18]:
torch.rand(3,4)

tensor([[0.1291, 0.1085, 0.4977, 0.1836],
        [0.6399, 0.5412, 0.8739, 0.9029],
        [0.6911, 0.7000, 0.4426, 0.3203]])

In [19]:
torch.randn(3,4)

tensor([[-0.1671, -0.3100, -0.3688,  1.1759],
        [ 2.0601, -1.3530, -0.4802,  0.1087],
        [ 1.1550,  1.6991, -2.5159, -0.8967]])

## torch.randint

产生一个由`[low,high)`区间均匀分布随机数填充的LongTensor

```python
randint(low=0,high,size,...)
```

In [20]:
torch.randint(1,10,(3,4))

tensor([[2, 3, 8, 6],
        [4, 4, 8, 3],
        [7, 5, 8, 1]])

## torch.randperm

生成一个随机全排列的一维的LongTensor

In [21]:
torch.randperm(12)

tensor([ 9, 10,  3,  5,  7,  4, 11,  0,  6,  1,  2,  8])

# 使用`xx_like`系列创建相同形态的Tensor

除了shape保持一致外，`dtype`、`layout`、`device`等，若无特别指定，则也与源Tensor保持一致。

```python
torch.zeros_like(input, ..) # 返回与input相同size的零矩阵

torch.ones_like(input, ..) #返回与input相同size的单位矩阵

torch.full_like(input, fill_value, …) #返回与input相同size，单位值为fill_value的矩阵

torch.empty_like(input, …) # 返回与input相同size,并被未初始化的数值填充的tensor

torch.rand_like(input, dtype=None, …) #返回与input相同size的tensor, 填充均匀分布的随机数值

torch.randint_like(input, low=0, high, dtype=None, …) #返回与input相同size的tensor, 填充[low, high)均匀分布的随机数值

torch.randn_like(input, dtype=None, …) #返回与input相同size的tensor, 填充标准正态分布的随机数值

```

In [22]:
src = torch.randn(4,5)

In [23]:
torch.zeros_like(src)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [24]:
torch.ones_like(src, dtype=torch.int)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [25]:
torch.empty_like(src, device='cuda:0')

tensor([[1., 2., 3., 4., 5.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0')

In [26]:
# 这里即使full_value是int类型，但生成的Tensor，依然是用的src的dtype
torch.full_like(src, 42)

tensor([[42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42.]])

In [27]:
torch.rand_like(src)

tensor([[0.6990, 0.0617, 0.0418, 0.0900, 0.9830],
        [0.8164, 0.1852, 0.2386, 0.2956, 0.3999],
        [0.4655, 0.1092, 0.7640, 0.1811, 0.5279],
        [0.9435, 0.7238, 0.1428, 0.0752, 0.1228]])

In [28]:
torch.randn_like(src)

tensor([[ 0.9366,  0.1560,  0.6002,  1.3912,  0.5083],
        [ 1.1414,  2.5705, -0.3684, -0.0108, -0.2299],
        [-0.7489,  0.0045,  0.2403,  1.0501,  1.1373],
        [-0.4165,  1.2640,  0.7514, -0.1586,  0.4076]])

In [29]:
torch.randint_like(src, 1, 10)

tensor([[2., 1., 8., 1., 5.],
        [7., 7., 2., 6., 4.],
        [9., 7., 6., 5., 3.],
        [4., 4., 8., 7., 6.]])